---
name: XML-CompareML
version: v0.2.5
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
abstract: A processor for the CompareML markup language
license: mit
resources:
  Demo: http://better-scm.berlios.de/comparison/
  Repository: https://svn.berlios.de/svnroot/repos/web-cpan/xml-compareml/
  homepage: http://web-cpan.berlios.de/modules/XML-CompareML/
  license: http://www.opensource.org/licenses/mit-license.php
build_requires:
  IO::Scalar: 0
  Test::Differences: 0
  Test::More: 0
requires:
  CGI: 0
  Class::Accessor: 0
  XML::LibXML: 0
  XML::LibXML::Common: 0
  XML::LibXSLT: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.3306
provides:
  XML::CompareML:
    file: lib/XML/CompareML.pm
    version: v0.2.5
  XML::CompareML::Base:
    file: lib/XML/CompareML/Base.pm
  XML::CompareML::DTD::Generate:
    file: lib/XML/CompareML/DTD/Generate.pm
  XML::CompareML::DocBook:
    file: lib/XML/CompareML/DocBook.pm
  XML::CompareML::HTML:
    file: lib/XML/CompareML/HTML.pm
generated_by: Module::Build version 0.3306
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - Better SCM
  - categories
  - compare
  - CompareML
  - comparison
  - criteria
  - criterion
  - grammar
  - language
  - markup
  - scm-comparison
  - systems
  - tree
  - version control
  - xml
  - XML
