---
abstract: 'A processor for the CompareML markup language'
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
build_requires:
  IO::Scalar: 0
  Test::Differences: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132140'
keywords:
  - 'Better SCM'
  - categories
  - compare
  - CompareML
  - comparison
  - criteria
  - criterion
  - grammar
  - language
  - markup
  - scm-comparison
  - systems
  - tree
  - 'version control'
  - xml
  - XML
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-CompareML
provides:
  XML::CompareML:
    file: lib/XML/CompareML.pm
    version: v0.2.8
  XML::CompareML::Base:
    file: lib/XML/CompareML/Base.pm
  XML::CompareML::DTD::Generate:
    file: lib/XML/CompareML/DTD/Generate.pm
  XML::CompareML::DocBook:
    file: lib/XML/CompareML/DocBook.pm
  XML::CompareML::HTML:
    file: lib/XML/CompareML/HTML.pm
requires:
  CGI: 0
  Class::Accessor: 0
  XML::LibXML: 0
  XML::LibXML::Common: 0
  XML::LibXSLT: 0
  strict: 0
  warnings: 0
resources:
  Demo: http://better-scm.berlios.de/comparison/
  homepage: http://web-cpan.berlios.de/modules/XML-CompareML/
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://bitbucket.org/shlomif/xml-compareml
version: v0.2.8
