---
name: XML-CompareML
version: 0.2.4
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
abstract: A processor for the CompareML markup language
license: mit
resources:
  license: http://opensource.org/licenses/mit-license.php
requires:
  CGI: 0
  Class::Accessor: 0
  XML::LibXML: 0
  XML::LibXML::Common: 0
  strict: 0
  warnings: 0
build_requires:
  IO::Scalar: 0
  Test::Differences: 0
  Test::More: 0
provides:
  XML::CompareML:
    file: lib/XML/CompareML.pm
    version: 0.2.4
  XML::CompareML::Base:
    file: lib/XML/CompareML/Base.pm
  XML::CompareML::DTD::Generate:
    file: lib/XML/CompareML/DTD/Generate.pm
  XML::CompareML::DocBook:
    file: lib/XML/CompareML/DocBook.pm
  XML::CompareML::HTML:
    file: lib/XML/CompareML/HTML.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
