---
name: XML-CompareML
version: 0.2.1
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
abstract: A processor for the CompareML markup language
license: bsd
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
requires:
  Class::Accessor: 0
  IO::Scalar: 0
  Test::More: 0
  XML::LibXML: 0
provides:
  XML::CompareML:
    file: lib/XML/CompareML.pm
    version: 0.2.1
  XML::CompareML::Base:
    file: lib/XML/CompareML/Base.pm
  XML::CompareML::DTD::Generate:
    file: lib/XML/CompareML/DTD/Generate.pm
  XML::CompareML::DocBook:
    file: lib/XML/CompareML/DocBook.pm
  XML::CompareML::HTML:
    file: lib/XML/CompareML/HTML.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
