--- #YAML:1.0
name: XML-CompareML
version: 0.2.0
license: bsd
distribution_type: module
requires:
  Class::Accessor: 0
  IO::Scalar: 0
  Test::More: 0
  XML::LibXML: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  XML::CompareML:
    file: lib/XML/CompareML.pm
    version: 0.2.0
  XML::CompareML::Base:
    file: lib/XML/CompareML/Base.pm
  XML::CompareML::DTD::Generate:
    file: lib/XML/CompareML/DTD/Generate.pm
  XML::CompareML::DocBook:
    file: lib/XML/CompareML/DocBook.pm
  XML::CompareML::HTML:
    file: lib/XML/CompareML/HTML.pm
generated_by: Module::Build version 0.21
